Restaurant.create!(name: "La Bonne Fourchette", address: "75008 Paris", category: "french")
Restaurant.create!(name: "Pearl Harbor", address: "75011 Paris", category: "japanese")
Restaurant.create!(name: "Chez Luiggi", address: "75003 Paris", category: "italian")
Restaurant.create!(name: "Soup Dog", address: "75013 Paris", category: "chinese")
Restaurant.create!(name: "Une Fois Mais Pas 2", address: "75004 Paris", category: "belgian")
